version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-players
    environment:
      MYSQL_ROOT_PASSWORD: navigator
      MYSQL_DATABASE: player_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      retries: 3
      start_period: 5s


networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local

