version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:5.7
    container_name: mysql-players
    environment:
      MYSQL_ROOT_PASSWORD: navigator
      MYSQL_DATABASE: player_db

    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app_network

  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
    driver: local
  mongodb_data:
    driver: local